{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibslack/1.0.1-SNAPSHOT/klibslack-1.0.1-SNAPSHOT.module",
    "group": "org.jraf.klibslack",
    "module": "klibslack",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibslack-jvm-1.0.1-SNAPSHOT.jar",
          "url": "klibslack-jvm-1.0.1-SNAPSHOT.jar",
          "size": 202732,
          "sha512": "3c933971edc3e7543e4cb003ab3fe341cdd0e0781fc48651cf736414fb3f383cef9e0731d3be30b67c614a13d293c72477589ea39dbdd7151d88cedde03ae0a7",
          "sha256": "656d572fccf615ffe42e533fa6ca9549afdba46cd63426481c36ec62878d5877",
          "sha1": "ee0398f72d62280835e3b3802a43961773518a90",
          "md5": "d0f2e8456978cd2b91028cdf223e7376"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.10.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.0.0",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibslack-jvm-1.0.1-SNAPSHOT.jar",
          "url": "klibslack-jvm-1.0.1-SNAPSHOT.jar",
          "size": 202732,
          "sha512": "3c933971edc3e7543e4cb003ab3fe341cdd0e0781fc48651cf736414fb3f383cef9e0731d3be30b67c614a13d293c72477589ea39dbdd7151d88cedde03ae0a7",
          "sha256": "656d572fccf615ffe42e533fa6ca9549afdba46cd63426481c36ec62878d5877",
          "sha1": "ee0398f72d62280835e3b3802a43961773518a90",
          "md5": "d0f2e8456978cd2b91028cdf223e7376"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibslack-jvm-1.0.1-SNAPSHOT-sources.jar",
          "url": "klibslack-jvm-1.0.1-SNAPSHOT-sources.jar",
          "size": 30521,
          "sha512": "268bc4575df7a7b966e5d19c9b26ea1505dd4315ea094ff01f580155e5f81ca16613f5580eb80085a6d527339425db3bb2acc5f156a4d4e61167076319ffc11c",
          "sha256": "438bf1b990e9fa7caae3dd74068cfea44b60746d2bd62edd9dc198b6ff5a4d96",
          "sha1": "dd416cc4b3ca287dab31c95cf7d10023cdd8af1f",
          "md5": "d28f1cdd8c0c6a027d856daab8533b74"
        }
      ]
    }
  ]
}
