{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibslack/1.0.3-SNAPSHOT/klibslack-1.0.3-SNAPSHOT.module",
    "group": "org.jraf.klibslack",
    "module": "klibslack",
    "version": "1.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibslack-jvm-1.0.3-SNAPSHOT.jar",
          "url": "klibslack-jvm-1.0.3-SNAPSHOT.jar",
          "size": 202881,
          "sha512": "dcc9a07dcf6d8932adf83be5ce9a5a83240f2cb34a35fcf579096a148eb80c906f0a20102aed46ca64209cff0591b21b0545db377a1eb8993605b61a837b4cea",
          "sha256": "19eed6bbf41d64e5503a5f4bf7949c193de0613e11b565857bb04a321ed20399",
          "sha1": "d0a6c8a29f8d56334320682cdaafe2a41844481d",
          "md5": "62ac5b11274dd51c0ca82e4af5e06c03"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibslack-jvm-1.0.3-SNAPSHOT.jar",
          "url": "klibslack-jvm-1.0.3-SNAPSHOT.jar",
          "size": 202881,
          "sha512": "dcc9a07dcf6d8932adf83be5ce9a5a83240f2cb34a35fcf579096a148eb80c906f0a20102aed46ca64209cff0591b21b0545db377a1eb8993605b61a837b4cea",
          "sha256": "19eed6bbf41d64e5503a5f4bf7949c193de0613e11b565857bb04a321ed20399",
          "sha1": "d0a6c8a29f8d56334320682cdaafe2a41844481d",
          "md5": "62ac5b11274dd51c0ca82e4af5e06c03"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibslack-jvm-1.0.3-SNAPSHOT-sources.jar",
          "url": "klibslack-jvm-1.0.3-SNAPSHOT-sources.jar",
          "size": 30521,
          "sha512": "d4b03695819d8dcf23c0e4ac0158251cea5b9089e0a8d8092fa68487694b5faae8dba92024495976969efaa07f68f22231527b05e55d78cabab06f22b86e562e",
          "sha256": "5ad0c33591394ae37ce6c578b1a77a77bc3527192c4731f242ffdc982f624777",
          "sha1": "4a540cd7a2776efacfe442de20981ef44e1911cb",
          "md5": "8fa0f5952f022b1ce9bae4fde61b43fd"
        }
      ]
    }
  ]
}
