{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibslack/1.0.2-SNAPSHOT/klibslack-1.0.2-SNAPSHOT.module",
    "group": "org.jraf.klibslack",
    "module": "klibslack",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibslack-jvm-1.0.2-SNAPSHOT.jar",
          "url": "klibslack-jvm-1.0.2-SNAPSHOT.jar",
          "size": 202646,
          "sha512": "7d5930a86621d90f737b50eaf3d5907452449048886422db053ae1f7221f8a564ec8ea5e8f51544911489a4e94a0636d5014883a8535f9473fa9103708d3c1cb",
          "sha256": "1e1b63d53e459ec4b08b8fc4d3b84d86e2d212875ff2760b0734e379fb604765",
          "sha1": "fe43c44c6576e76c3d76ad90555d5a0712dda43d",
          "md5": "b85271535c37daaf0c8ac8b2dea4a958"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.10.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.0.0",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibslack-jvm-1.0.2-SNAPSHOT.jar",
          "url": "klibslack-jvm-1.0.2-SNAPSHOT.jar",
          "size": 202646,
          "sha512": "7d5930a86621d90f737b50eaf3d5907452449048886422db053ae1f7221f8a564ec8ea5e8f51544911489a4e94a0636d5014883a8535f9473fa9103708d3c1cb",
          "sha256": "1e1b63d53e459ec4b08b8fc4d3b84d86e2d212875ff2760b0734e379fb604765",
          "sha1": "fe43c44c6576e76c3d76ad90555d5a0712dda43d",
          "md5": "b85271535c37daaf0c8ac8b2dea4a958"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibslack-jvm-1.0.2-SNAPSHOT-sources.jar",
          "url": "klibslack-jvm-1.0.2-SNAPSHOT-sources.jar",
          "size": 30520,
          "sha512": "19ba1b606ac63e95618778ccff67a1ba62d01788bd33bcaaab7756bf39067c3efa0d49305439881d48d740e1ae472f47ee8c83c052e5a547aded111876283fa1",
          "sha256": "545bdaa3afbc7fb8542fc0681bfd11edce06f3783b82988d22b6cfa138e261c9",
          "sha1": "08cb87895d922204f07c4b9715968027a454ae6d",
          "md5": "35cc4ee95ad8d83918e54b5062ab351b"
        }
      ]
    }
  ]
}
