{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibslack/1.0.1/klibslack-1.0.1.module",
    "group": "org.jraf.klibslack",
    "module": "klibslack",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibslack-jvm-1.0.1.jar",
          "url": "klibslack-jvm-1.0.1.jar",
          "size": 202637,
          "sha512": "caf023fcacd5551c6bcf455580ef2a14c163413c8b3258c75df21bb0c77be9a754f1d03ae7293750ca2673a2662fa796ea71a1f9d1c691aa1d5ea09f9fdf22a1",
          "sha256": "ac5d4deede2fa19098265625f11847a5d5520300e0971571cbb8e54b28894bc3",
          "sha1": "c52ec587e92f750240941234491e185e5804421d",
          "md5": "b99c8d6298fdf0766af7c3ec8d947730"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.10.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.0.0",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibslack-jvm-1.0.1.jar",
          "url": "klibslack-jvm-1.0.1.jar",
          "size": 202637,
          "sha512": "caf023fcacd5551c6bcf455580ef2a14c163413c8b3258c75df21bb0c77be9a754f1d03ae7293750ca2673a2662fa796ea71a1f9d1c691aa1d5ea09f9fdf22a1",
          "sha256": "ac5d4deede2fa19098265625f11847a5d5520300e0971571cbb8e54b28894bc3",
          "sha1": "c52ec587e92f750240941234491e185e5804421d",
          "md5": "b99c8d6298fdf0766af7c3ec8d947730"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibslack-jvm-1.0.1-sources.jar",
          "url": "klibslack-jvm-1.0.1-sources.jar",
          "size": 30513,
          "sha512": "bb90f3ad938f0190157af231e7a624b3d74f6136ceb42ddca632648eadc7ad7482c63aec5be347ed8450c4c117043ee2ddf03e764d6ffbec490ae696be79a7f0",
          "sha256": "b1997b87ec4bb87174642dd22eaf9cae48887cd8b9770d9eff29ab5873ea384a",
          "sha1": "9e8b360c102123c0442131603d5f58959101e464",
          "md5": "ef169a449415036e223e0f10c2cf7500"
        }
      ]
    }
  ]
}
