{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibslack/1.0.0-SNAPSHOT/klibslack-1.0.0-SNAPSHOT.module",
    "group": "org.jraf.klibslack",
    "module": "klibslack",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibslack-jvm-1.0.0-SNAPSHOT.jar",
          "url": "klibslack-jvm-1.0.0-SNAPSHOT.jar",
          "size": 202732,
          "sha512": "d8d25fca6aefbe479d6d094afefec5f17e23acc25274954df5fcef6e8c22e0b8bceff00218b89df6c9f7ac24d2778b69ac6e37e2c53a25b1927eb21f7a07c2c8",
          "sha256": "eb0e0b770d8f293c86517633645fa0f4aa3f3086c20d73a6cdbb3c6ecc603eb0",
          "sha1": "2e0adfdff5340bd6804dd30c5fea226c1d6ac7c9",
          "md5": "fd8ce44b99653aa1f8940f5a519dd421"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.10.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.0.0",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibslack-jvm-1.0.0-SNAPSHOT.jar",
          "url": "klibslack-jvm-1.0.0-SNAPSHOT.jar",
          "size": 202732,
          "sha512": "d8d25fca6aefbe479d6d094afefec5f17e23acc25274954df5fcef6e8c22e0b8bceff00218b89df6c9f7ac24d2778b69ac6e37e2c53a25b1927eb21f7a07c2c8",
          "sha256": "eb0e0b770d8f293c86517633645fa0f4aa3f3086c20d73a6cdbb3c6ecc603eb0",
          "sha1": "2e0adfdff5340bd6804dd30c5fea226c1d6ac7c9",
          "md5": "fd8ce44b99653aa1f8940f5a519dd421"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibslack-jvm-1.0.0-SNAPSHOT-sources.jar",
          "url": "klibslack-jvm-1.0.0-SNAPSHOT-sources.jar",
          "size": 30521,
          "sha512": "628089e2bb6c0e09a5c9a59e37c1dbbaf69734ad4120a61e4fa2aca0855e054ac2cbe621bf4ed51c21278b21c5ff2d88eff287bba19463bf8d61b363521c9f86",
          "sha256": "4b43c23987362f22ddd563da9226bcad3780a25a0c82887add8432eac9674aba",
          "sha1": "4d91084752b2005291d6da39bdd67bdc473785a0",
          "md5": "55b596f066eb57f21c1523e0b8c123f2"
        }
      ]
    }
  ]
}
